### ISSUE TITLE
No preview images displayed

### ISSUE THREAD

**Issue by phel0049** [fooblahblah/craigslistpreview#4]
I'm unsure as to why this issue was closed when the issue wasn't fixed?  Here's the comment I originally posted in the closed issue - the issue is not fixed:
I am having the same issue, extension isn't working at all since Friday at least. On ANY Craigslist page I visit, but here is the one I visit the most often if that is of help to you: http://minneapolis.craigslist.org/hnp/zip/ I have Google Chrome version 21.0.1180.60 m. Maybe something happenned in a recent Chrome update that broke the extension? I noticed at the same time the Craigslist icon (.ico) image stopped appearing in the address bar.

**Comment by fooblahblah** [comment]
I posted a new version of the extension which should fix the issue.  Make sure you're using v1.0.19

**Comment by phel0049** [comment]
Thanks - yes I uninstalled the extension and then re-installed and it works! Thank you!
