### ISSUE TITLE
No preview images displayed as of 9/25/12

### ISSUE THREAD

**Issue by phel0049** [fooblahblah/craigslistpreview#5]
Hi there - I haven't looked at craigslist for a few days, so I'm not sure when this stopped working for me, but Craigslist preview doesn't show any images for me right not.  I use Chrome 21.0.1180.89 (which I assume is the latest).

Thanks - I LOVE your extension.  Craigslist now has a "show images" option, but the pictures look really small (and only show one of multiple pics), so I still rely on your extension.  Thank you for all your work!!!

**Comment by fooblahblah** [comment]
Thanks for the feedback.  I'm looking at the Boulder Craigslist and the extension seems to be working.  I fixed a couple issues in 1.0.19.  I've noticed that Chrome doesn't always update to the latest extension version.  You can double-check by going to Tools/Extensions in the menu and verify your version.  If the version you have is old you might try using that Update Extensions button.

If you're on the latest cab you post a link to the example page you're seeing it bust on?
