### ISSUE TITLE
Layout Issues

### ISSUE THREAD

**Issue by geeknik** [fooblahblah/craigslistpreview#6]
I'm seeing some layout issues when using your extension and Chrome version 25.0.1323.1 dev-m.

screenshot: http://i.imgur.com/mcxqP.png

**Comment by fooblahblah** [comment]
Thanks for the heads up.  I'll install the dev build and check it out.

**Comment by fooblahblah** [comment]
Should be fixed now.  Thanks for reporting the bug.
